### ISSUE TITLE
Latest pushed windows image incorrect version

### ISSUE THREAD

**Issue by Jonny-vb** [jenkinsci/docker#2033]
The latest versions of the windows docker images pushed to dockerhub are not the latest version.
I run with the `jenkins/jenkins:windowsservercore-ltsc2019` tag and expect this to be the latest version.
However on updating this week this tag now looks like it points to a build of 2.476 (previous was 2.515, I was expecting to update to 2.516) which causes Jenkins to not launch (I assume due to some plugin incompatibility)

**Comment by dduportal** [comment]
Thanks @Jonny-vb for reporting. We are back to the same issue as before: the private controller trusted.ci.jenkins.io did trigger old tags while it should not.

I really don't understand why: the job is setup to NOT trigger tags older than 7 days.

On the short time being, we have trigger a rebuild of the Docker image for 2.516: you should have your problem fixed in ~20 min.

**Comment by Jonny-vb** [comment]
Thanks for resolving @dduportal.
I've since manually updated to the latest release tag 2.516 and I still can't start jenkins - I'm getting the log below out. Any chance you know what could be going on?

<details>
<summary>Log</summary>

```
:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe� dministrator: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe�P icked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Running from: C:\ProgramData\jenkins\jenkins.war
webroot: C:\ProgramData\Jenkins\JenkinsHome\war

2025-06-26 08:51:18.376+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2025-06-26 08:51:18.489+0000 [id=1]     WARNING o.e.j.ee9.nested.ContextHandler#setContextPath: Empty contextPath
2025-06-26 08:51:18.646+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-12.0.22; built: 2025-06-02T15:25:31.946Z; git: 335c9ab44a5591f0ea941bf350e139b8c4f5537c; jvm 21.0.7+6-LTSP
2025-06-26 08:51:19.831+0000 [id=1]     INFO    o.e.j.e.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.ee9.jsp.JettyJspServlet
2025-06-26 08:51:19.951+0000 [id=1]     INFO    o.e.j.s.DefaultSessionIdManager#doStart: Session workerName=node0
2025-06-26 08:51:20.668+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: C:\ProgramData\Jenkins\JenkinsHome found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2025-06-26 08:51:20.853+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started oeje9n.ContextHandler$CoreContextHandler@4565a70a{Jenkins v2.516,/,b=file:///C:/ProgramData/jenkins/jenkinshome/war/,a=AVAILABLE,h=oeje9n.ContetHandler$CoreContextHandler$CoreToNestedHandler@a0a9fa5{STARTED}}
2025-06-26 08:51:20.877+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@758714af{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2025-06-26 08:51:20.919+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started oejs.Server@1a6d8329{STARTING}[12.0.22,sto=0] @3751ms
2025-06-26 08:51:20.922+0000 [id=38]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2025-06-26 08:51:21.122+0000 [id=37]    INFO    jenkins.model.Jenkins#<init>: Starting version 2.516s
2025-06-26 08:51:21.254+0000 [id=44]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initializationd
2025-06-26 08:51:21.649+0000 [id=47]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2025-06-26 08:51:28.910+0000 [id=54]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins.
2025-06-26 08:51:28.962+0000 [id=43]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2025-06-26 08:51:28.970+0000 [id=48]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2025-06-26 08:51:30.326+0000 [id=52]    INFO    h.p.b.g.GlobalTimeOutConfiguration#load: global timeout not set2
2025-06-26 08:51:30.850+0000 [id=47]    WARNING h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=org.jenkinsci.plugins.mailwatcher.WatcherComputerListener, annotation=[none]]; skipping this component java.lang.ClassNotFoundException: hudson.plugins.jobConfigHistory.JobConfigHistory
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:64)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
Caused: java.lang.NoClassDefFoundError: hudson/plugins/jobConfigHistory/JobConfigHistory
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.MailWatcherMailer.<init>(MailWatcherMailer.java:67)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherComputerListener.<init>(WatcherComputerListener.java:57)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherComputerListener$$FastClassByGuice$$55ce67c8.GUICE$TRAMPOLINE(<generated>)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherComputerListener$$FastClassByGuice$$55ce67c8.apply(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:613)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: hudson/plugins/jobConfigHistory/JobConfigHistory  at WatcherComputerListener.<init>(WatcherComputerListener.java:56)
Learn more:  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================Full classname legend:======================WatcherComputerListener: "org.jenkinsci.plugins.mailwatcher.WatcherComputerListener"========================End of classname legend:========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:448)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:406)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:397)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:353)
        at hudson.ExtensionList.load(ExtensionList.java:405)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:324)
        at hudson.ExtensionList.iterator(ExtensionList.java:176)
        at jenkins.util.Listeners.lambda$notify$0(Listeners.java:57)
        at jenkins.util.Listeners.notify(Listeners.java:70)
        at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:278)
        at jenkins.model.Jenkins.updateComputers(Jenkins.java:1617)
        at jenkins.model.Jenkins.load(Jenkins.java:3391)
        at jenkins.model.Jenkins$13.run(Jenkins.java:3484)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:304)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

2025-06-26 08:51:30.937+0000 [id=47]    WARNING hudson.model.Slave#warnPlugin: hudson.slaves.DumbSlave or one of its superclass overrides readResolve() without calling super implementation.Please file an issue against the plugin implementing it: null 2025-06-26 08:51:31.026+0000 [id=47]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2025-06-26 08:51:31.031+0000 [id=43]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2025-06-26 08:51:31.186+0000 [id=53]    WARNING h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=org.jenkinsci.plugins.mailwatcher.NodeAwailabilityListener, annotation=[none]]; skipping this componentjava.lang.ClassNotFoundException: hudson.plugins.jobConfigHistory.JobConfigHistory
Caused: java.lang.NoClassDefFoundError: hudson/plugins/jobConfigHistory/JobConfigHistory
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.MailWatcherMailer.<init>(MailWatcherMailer.java:67)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.NodeAwailabilityListener.<init>(NodeAwailabilityListener.java:62)

        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.NodeAwailabilityListener$$FastClassByGuice$$55b28e41.GUICE$TRAMPOLINE(<generated>)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.NodeAwailabilityListener$$FastClassByGuice$$55b28e41.apply(<generated>)

        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:613)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: hudson/plugins/jobConfigHistory/JobConfigHistory  at NodeAwailabilityListener.<init>(NodeAwailabilityListener.java:61)
Learn more:  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================Full classname legend:======================NodeAwailabilityListener: "org.jenkinsci.plugins.mailwatcher.NodeAwailabilityListener"========================End of classname legend:========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:448)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:406)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:397)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:353)
        at hudson.ExtensionList.load(ExtensionList.java:405)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:324)
        at hudson.ExtensionList.iterator(ExtensionList.java:176)
        at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Unknown Source)
        at java.base/java.util.Spliterator.getExactSizeIfKnown(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.exactOutputSizeIfKnown(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
        at hudson.model.RunMap.createLoadAllower(RunMap.java:269)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.loadNumberOnDisk(AbstractLazyLoadRunMap.java:347)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.initBaseDir(AbstractLazyLoadRunMap.java:304)
        at hudson.model.RunMap.<init>(RunMap.java:101)
        at jenkins.model.lazy.LazyBuildMixIn.createBuildRunMap(LazyBuildMixIn.java:143)
        at jenkins.model.lazy.LazyBuildMixIn.onLoad(LazyBuildMixIn.java:107)
        at PluginClassLoader for workflow-job//org.jenkinsci.plugins.workflow.job.WorkflowJob.onLoad(WorkflowJob.java:142)
        at hudson.model.Items.load(Items.java:376)
        at jenkins.model.Jenkins$14.run(Jenkins.java:3504)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:304)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

2025-06-26 08:51:32.756+0000 [id=47]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobsd
2025-06-26 08:51:32.829+0000 [id=46]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated 2025-06-26 08:51:32.955+0000 [id=46]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization 2025-06-26 08:51:33.234+0000 [id=37]    WARNING h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=org.jenkinsci.plugins.mailwatcher.WatcherItemListener, annotation=[none]]; skipping this component
java.lang.ClassNotFoundException: hudson.plugins.jobConfigHistory.JobConfigHistory
Caused: java.lang.NoClassDefFoundError: hudson/plugins/jobConfigHistory/JobConfigHistory
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.MailWatcherMailer.<init>(MailWatcherMailer.java:67)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherItemListener.<init>(WatcherItemListener.java:57)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherItemListener$$FastClassByGuice$$55d332d2.GUICE$TRAMPOLINE(<generated>)
        at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherItemListener$$FastClassByGuice$$55d332d2.apply(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:613)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: hudson/plugins/jobConfigHistory/JobConfigHistory  at WatcherItemListener.<init>(WatcherItemListener.java:56)
Learn more:  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================Full classname legend:======================WatcherItemListener:  "org.jenkinsci.plugins.mailwatcher.WatcherItemListener"
========================End of classname legend:========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:448)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:406)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:397)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:353)
        at hudson.ExtensionList.load(ExtensionList.java:405)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:324)
        at hudson.ExtensionList.iterator(ExtensionList.java:176)
        at jenkins.model.Jenkins.<init>(Jenkins.java:1035)
        at hudson.model.Hudson.<init>(Hudson.java:102)
        at hudson.model.Hudson.<init>(Hudson.java:87)
        at hudson.WebAppMain$3.run(WebAppMain.java:249)
2025-06-26 08:51:33.247+0000 [id=37]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
``` 

</details>

**Comment by dduportal** [comment]
@Jonny-vb for information, the Docker image tag `windowsservercore-ltsc2019` is now fixed in the DockerHub

![Image](https://github.com/user-attachments/assets/2dc520eb-e540-4676-991f-03818eda093b)

**Comment by dduportal** [comment]
> Thanks for resolving [@dduportal](https://github.com/dduportal). I've since manually updated to the latest release tag 2.516 and I still can't start jenkins - I'm getting the log below out. Any chance you know what could be going on?
> Log

The error stack seems related to the job config history plugin. Did you run the image "as it" or do you have an already existing JENKINS_HOME with plugins?

**Comment by Jonny-vb** [comment]
I have a jenkinshome volume setup that I carry into every new image (including the accidental "update" to 2.476)

**Comment by Jonny-vb** [comment]
I have since rolled back to specifying the 2.515 tag and tried installing the job config plugin via the jenkins-plugin-manager cli (I'm not sure I've ever had this plugin before, so not sure why it was causing an error).
I now don't get any errors, but I still can't connect to jenkins via a browser

The thing I find confusing is that the last line in both logs indicates that jenkins is up and running so should be accessible...

I have also tried another instance with no volume for jenkinshome (i.e. fresh install) and this does come up as expected 

<details>
<summary> Log </summary>

```

:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe administrator: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Running from: C:\ProgramData\jenkins\jenkins.war
webroot: C:\ProgramData\Jenkins\JenkinsHome\war
2025-06-26 11:29:23.481+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war fileX
P2025-06-26 11:29:23.613+0000 [id=1]     WARNING o.e.j.ee9.nested.ContextHandler#setContextPath: Empty contextPathX
P2025-06-26 11:29:23.756+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-12.0.22; built: 2025-06-02T15:25:31.946Z; git: 335c9ab44a5591f0ea941bf350e139b8c4f5537c; jvm 21.0.7+6-LTSX
P2025-06-26 11:29:24.969+0000 [id=1]     INFO    o.e.j.e.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.ee9.jsp.JettyJspServletX
P2025-06-26 11:29:25.089+0000 [id=1]     INFO    o.e.j.s.DefaultSessionIdManager#doStart: Session workerName=node0X
P2025-06-26 11:29:25.871+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: C:\ProgramData\Jenkins\JenkinsHome found at: EnvVars.masterEnvVars.get("JENKINS_HOME")X
P2025-06-26 11:29:26.069+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started oeje9n.ContextHandler$CoreContextHandler@4565a70a{Jenkins v2.515,/,b=file:///C:/ProgramData/jenkins/jenkinshome/war/,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@a0a9fa5{STARTED}}X
P2025-06-26 11:29:26.104+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@4525d1d3{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
P2025-06-26 11:29:26.161+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started oejs.Server@1a6d8329{STARTING}[12.0.22,sto=0] @4025ms

2025-06-26 11:29:26.168+0000 [id=38]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2025-06-26 11:29:26.352+0000 [id=37]    INFO    jenkins.model.Jenkins#<init>: Starting version 2.515s
2025-06-26 11:29:26.490+0000 [id=44]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initializationd
2025-06-26 11:29:26.907+0000 [id=46]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
22025-06-26 11:29:34.743+0000 [id=47]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins.
2025-06-26 11:29:34.808+0000 [id=48]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2025-06-26 11:29:34.821+0000 [id=48]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2025-06-26 11:29:36.244+0000 [id=45]    INFO    h.p.b.g.GlobalTimeOutConfiguration#load: global timeout not set
22025-06-26 11:29:36.775+0000 [id=44]    WARNING hudson.model.Slave#warnPlugin: hudson.slaves.DumbSlave or one of its superclass overrides readResolve() without calling super implementation.Please file an issue against the plugin implementing it: null
22025-06-26 11:29:36.868+0000 [id=44]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2025-06-26 11:29:36.880+0000 [id=52]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2025-06-26 11:29:38.892+0000 [id=45]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2025-06-26 11:29:38.903+0000 [id=50]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2025-06-26 11:29:38.990+0000 [id=52]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization2
2025-06-26 11:29:39.420+0000 [id=37]    INFO    o.j.p.m.MailWatcherNotification#log: mail-watcher-plugin: unable to notify java.net.ConnectException: Connection refused: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at PluginClassLoader for jakarta-mail-api//org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:366)
	at PluginClassLoader for jakarta-mail-api//org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:243)
	at PluginClassLoader for jakarta-mail-api//org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2193)X

Caused: org.eclipse.angus.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout 60000;
nested exception is: java.net.ConnectException: Connection refused: getsockopt
	at PluginClassLoader for jakarta-mail-api//org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2243)
	at PluginClassLoader for jakarta-mail-api//org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:729)
	at PluginClassLoader for jakarta-mail-api//jakarta.mail.Service.connect(Service.java:345)
	at PluginClassLoader for jakarta-mail-api//jakarta.mail.Service.connect(Service.java:225)
	at PluginClassLoader for jakarta-mail-api//jakarta.mail.Service.connect(Service.java:174)
	at PluginClassLoader for jakarta-mail-api//jakarta.mail.Transport.send0(Transport.java:232)
	at PluginClassLoader for jakarta-mail-api//jakarta.mail.Transport.send(Transport.java:102)
	at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.MailWatcherMailer.send(MailWatcherMailer.java:138)
	at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.MailWatcherMailer.send(MailWatcherMailer.java:131)
	at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.MailWatcherNotification.send(MailWatcherNotification.java:156)
	at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherComputerListener$Notification$Builder.send(WatcherComputerListener.java:182)
	at PluginClassLoader for mail-watcher-plugin//org.jenkinsci.plugins.mailwatcher.WatcherComputerListener.onOnline(WatcherComputerListener.java:104)
	at jenkins.model.Jenkins.<init>(Jenkins.java:1022)
	at hudson.model.Hudson.<init>(Hudson.java:102)
	at hudson.model.Hudson.<init>(Hudson.java:87)
	at hudson.WebAppMain$3.run(WebAppMain.java:249)X

2025-06-26 11:29:39.441+0000 [id=37]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and runningX

```

</details>

**Comment by dduportal** [comment]
> this does come up as expected

🤔 does the "empty jenkins from scratch" starts with no issue, or does it starts with no access? (I'm asking as the quoted sentence is making me confused, so I prefer be sure to understand)

**Comment by Jonny-vb** [comment]
Sorry - I mean that it starts as I'd expect from a clean container - so I can access it via a browser but need to go through the setup process with entering the admin password

**Comment by dduportal** [comment]
@Jonny-vb interesting 🤔  What happens if you remove the plugin from `$JENKINS_HOME/plugins` at all?

**Comment by Jonny-vb** [comment]
Okay I've got in there in the end - it looks like somewhere along all this happening I just lost the ssl config from the container... 🤦
Thanks for your help and for resolving the original issue @dduportal !
