### ISSUE TITLE
[JENKINS-33412] Jenkins curl 8080 not working although the container shows not failure logs

### ISSUE THREAD

**Issue by pranshuverma** [jenkinsci/docker#702]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Command executed
`docker run --name jenkins -d --env JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties" -e DEBUG=true -p 8080:8080 -v $PWD/jenkins:/var/jenkins_home jenkins/jenkins:lts`

### Output of `docker version`
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

### Other relevant information
I have changed the ownership of $PWD/jenkins folder to user 1000.
log.properties are set based on github documentation
```
cat > $PWD/jenkins/log.properties <<EOF
handlers=java.util.logging.ConsoleHandler
jenkins.level=FINEST
java.util.logging.ConsoleHandler.level=FINEST
EOF
```

Tried on same host with earlier version from dockerhub library/jenkins works.

**Comment by oleg-nenashev** [comment]
If you run with `-e DEBUG=true`, the container will be waiting for the debugger to attach to the port 5005. The port is not exposed, so obviously you are not attaching it. Just remove this debug variable, and everything will be fine

**Comment by pranshuverma** [comment]
@oleg-nenashev I pasted the wrong command. Its not working without  -e DEBUG=true option also.

Sorry for the inconvenience.

**Comment by oleg-nenashev** [comment]
Please provide the container logs then

**Comment by pranshuverma** [comment]
```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jul 02, 2018 12:41:09 PM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @384ms to org.eclipse.jetty.util.log.JavaUtilLog
Jul 02, 2018 12:41:10 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath
WARNING: Empty contextPath
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.util.RingBufferLogHandler.defaultSize => null
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: DefaultSessionIdManager workerName=node0
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: No SessionScavenger set, using defaults
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging
INFO: Scavenging every 600000ms
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Node.SKIP_BUILD_CHECK_ON_FLYWEIGHTS => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.logStartupPerformance => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Hudson.logStartupPerformance => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.slaveAgentPortEnforce => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.parallelLoad => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Hudson.parallelLoad => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.killAfterLoad => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Hudson.killAfterLoad => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.workspaceDirName => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Hudson.workspaceDirName => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): JENKINS_HOME => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): HUDSON_HOME => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Main.development => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Main.timeout => null
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.util.CharacterEncodingFilter.disableFilter => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.util.CharacterEncodingFilter.forceEncoding => null
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started w.@4b520ea8{/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.slaveAgentPort => null
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@b2b91a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Jul 02, 2018 12:41:10 PM org.eclipse.jetty.server.Server doStart
INFO: Started @1340ms
Jul 02, 2018 12:41:10 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): hudson.model.LoadStatistics.decay => 0.9
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.LoadStatistics.clock => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.NodeProvisioner.MARGIN => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.NodeProvisioner.MARGIN0 => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.NodeProvisioner.MARGIN_DECAY => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): hudson.model.UpdateCenter.updateCenterUrl => https://updates.jenkins.io/
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.UpdateCenter.pluginDownloadReadTimeoutSeconds => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): hudson.model.UpdateCenter.defaultUpdateSiteId => default
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.UpdateCenter.never => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): hudson.model.UpdateCenter.className => null
Jul 02, 2018 12:41:10 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Util.noSymLink => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Util.symlinkEscapeHatch => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Util.maxFileDeletionRetries => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Util.deletionRetryWait => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Util.performGCOnFailedDelete => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.Util.useNativeChmodAndMode => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.script.noCache => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.ProxyConfiguration.DEFAULT_CONNECT_TIMEOUT_MILLIS => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.PluginManager.noFastLookup => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.PluginManager.className => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.PluginManager.workDir => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.PluginStrategy => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.ClassicPluginStrategy.useAntClassLoader => null
Jul 02, 2018 12:41:11 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.ClassicPluginStrategy.noBytecodeTransformer => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.security.ClassFilterImpl.SUPPRESS_WHITELIST => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.security.ClassFilterImpl.SUPPRESS_ALL => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.InitReactorRunner.concurrency => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.initLogLevel => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Hudson.initLogLevel => null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Cleaning up obsolete items deleted from the disk
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Loading bundled plugins
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.bundled.plugins => null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Cleaning up obsolete items deleted from the disk
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Computer.relocateOldLogs
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started LogRecorderManager.init
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started InstallUncaughtExceptionHandler.init
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started CrumbIssuer.initStaplerCrumbIssuer
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.security.ExtendedReadPermission => null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Result.init
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Cleaning up obsolete items deleted from the disk
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed CrumbIssuer.initStaplerCrumbIssuer
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Computer.relocateOldLogs
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed LogRecorderManager.init
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed InstallUncaughtExceptionHandler.init
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Result.init
Jul 02, 2018 12:41:12 PM jenkins.install.InstallUtil getLastExecVersion
FINE: discovered serialized lastVersion 2.121.1
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Loading bundled plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Loading bundled plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Listing up plugins
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.bundled.plugins => null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Listing up plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Listing up plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Preparing plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Preparing plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Checking cyclic dependencies
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Checking cyclic dependencies
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Preparing plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Checking cyclic dependencies
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Loading plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Loading plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Discovering plugin initialization tasks
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Loading plugins
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Discovering plugin initialization tasks
Jul 02, 2018 12:41:12 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Discovering plugin initialization tasks
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.DownloadService.never => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.DownloadService.noSignatureCheck => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.AsyncPeriodicWork.logRotateMinutes => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.AsyncPeriodicWork.logRotateSize => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Queue.Saver.DELAY_SECONDS => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.UsageStatistics.disabled => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.User.SECURITY_243_FULL_DEFENSE => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.WorkspaceCleanupThread.disabled => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.WorkspaceCleanupThread.recurrencePeriodHours => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.WorkspaceCleanupThread.retainForDays => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ConnectionActivityMonitor.timeToPing => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ConnectionActivityMonitor.frequency => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ConnectionActivityMonitor.timeToPing => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.NodeProvisioner.initialDelay => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.NodeProvisioner.recurrencePeriod => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.lazy.BuildReference.MODE => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.security.ignoreBasicAuth => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): jenkins.security.FrameOptionsPageDecorator.enabled => true
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.Api.INSECURE => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.security.UserDetailsCache.EXPIRE_AFTER_WRITE_SEC => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.security.s2m.DefaultFilePathFilter.allow => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.slaves.JnlpSlaveAgentProtocol3.enabled => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.slaves.NioChannelSelector.disabled => null
Jul 02, 2018 12:41:12 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.slaves.StandardOutputSwapper.disabled => null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Resolving Dependant Plugins Graph
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Resolving Dependant Plugins Graph
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Contributed.load
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Resolving Dependant Plugins Graph
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.remoting.ClassFilter => null
Jul 02, 2018 12:41:13 PM jenkins.security.CustomClassFilter$Contributed load
FINE: plugin-defined entries: {}
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Contributed.load
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started RekeySecretAdminMonitor.scanOnReboot
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started UpdateCenter.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed RekeySecretAdminMonitor.scanOnReboot
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started NullIdDescriptorMonitor.verify
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started DownloadableListener.installListener
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Loading global config
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed DownloadableListener.installListener
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.TreeView => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.util.Secret.provider => null
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isLocationWhitelisted$2
FINE: file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar seems to be the location of Jenkins core, OK
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.util.PersistedList due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.Hudson due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.UpdateSite due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.UpdateCenter.never => null
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: tolerating java.lang.String by whitelist
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: tolerating java.util.concurrent.CopyOnWriteArraySet by whitelist
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: tolerating java.lang.Integer by whitelist
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.Node$Mode since it is an enum
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: tolerating java.lang.Boolean by whitelist
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.util.AtomicFileWriter.DISABLE_FORCED_FLUSH => null
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.security.FullControlOnceLoggedInAuthorizationStrategy due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.security.HudsonPrivateSecurityRealm due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: tolerating java.util.ArrayList by whitelist
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.views.DefaultViewsTabBar due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.views.DefaultMyViewsTabBar due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.Hudson$CloudList due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: tolerating java.util.concurrent.CopyOnWriteArrayList by whitelist
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.AllView due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.View$PropertyList due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.security.ExtendedReadPermission => null
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.security.csrf.DefaultCrumbIssuer due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.util.DescribableList due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.buildsDir => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.Jenkins.workspacesDir => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): debug.YUI => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.security.WipeOutPermission => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): hudson.slaves.WorkspaceList => @
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (default): hudson.security.csrf.requestfield => Jenkins-Crumb
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.DownloadService$Downloadable.defaultInterval => null
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting jenkins.CLI due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed NullIdDescriptorMonitor.verify
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ChannelPinger.pingTimeoutSeconds => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ChannelPinger.pingIntervalSeconds => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ChannelPinger.pingInterval => null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Loading global config
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Loading global config
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.os.solaris.ZFSInstaller.disabled => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.os.solaris.ZFSInstaller.migrate => null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started DoubleLaunchChecker.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Finalizing set up
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started GroovyInitScript.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started AperiodicWork.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started PeriodicWork.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Uptime.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started InitialUserContent.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started AllUsers.scanAll
Jul 02, 2018 12:41:13 PM jenkins.diagnosis.HsErrPidList scan
FINE: Scanning ./hs_err_pid%p.log for hs_err_pid files
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started Queue.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed DoubleLaunchChecker.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started QueueSorter.installDefaultQueueSorter
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started ComputerSet.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started SSHD.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed InitialUserContent.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskStarted
FINE: Started null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Uptime.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Queue.init
Jul 02, 2018 12:41:13 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.User.allowNonExistentUserToLogin => null
Jul 02, 2018 12:41:13 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.User.allowUserCreationViaUrl => null
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.node_monitors.ArchitectureMonitor due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.node_monitors.ClockMonitor due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.node_monitors.DiskSpaceMonitor due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.node_monitors.SwapSpaceMonitor due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.node_monitors.TemporarySpaceMonitor due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.node_monitors.ResponseTimeMonitor due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:13 PM jenkins.diagnosis.HsErrPidList scan
FINE: Scanning /tmp/hs_err_pid%p.log for hs_err_pid files
Jul 02, 2018 12:41:14 PM jenkins.model.Jenkins setSecurityRealm
FINE: HudsonFilter has been previously initialized: Setting security up
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed UpdateCenter.init
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed ComputerSet.init
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed SSHD.init
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed QueueSorter.installDefaultQueueSorter
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.User due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting jenkins.security.ApiTokenProperty due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.security.ApiTokenProperty.showTokenToAdmins => null
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.util.Secret due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.FingerprintCleanupThread.logRotateMinutes => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.FingerprintCleanupThread.logRotateSize => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.WorkspaceCleanupThread.logRotateMinutes => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.model.WorkspaceCleanupThread.logRotateSize => null
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.MyViewsProperty due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ConnectionActivityMonitor.logRotateMinutes => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ConnectionActivityMonitor.logRotateSize => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.slaves.ConnectionActivityMonitor.enabled => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.DownloadSettings$DailyCheck.logRotateMinutes => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): jenkins.model.DownloadSettings$DailyCheck.logRotateSize => null
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.model.PaneStatusProperties due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed AperiodicWork.init
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed PeriodicWork.init
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.search.UserSearchProperty due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.triggers.SafeTimerTask.logsTargetDir => null
Jul 02, 2018 12:41:14 PM jenkins.security.ClassFilterImpl lambda$isBlacklisted$1
FINE: permitting hudson.security.HudsonPrivateSecurityRealm$Details due to its location in file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.121.1.jar
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed AllUsers.scanAll
Jul 02, 2018 12:41:14 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 5 ms
Jul 02, 2018 12:41:14 PM jenkins.util.groovy.GroovyHookScript execute
INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed GroovyInitScript.init
Jul 02, 2018 12:41:14 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@7f8f5b07: display name [Root WebApplicationContext]; startup date [Mon Jul 02 12:41:14 UTC 2018]; root of context hierarchy
Jul 02, 2018 12:41:14 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@7f8f5b07]: org.springframework.beans.factory.support.DefaultListableBeanFactory@5d51a05f
Jul 02, 2018 12:41:14 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@5d51a05f: defining beans [authenticationManager]; root of factory hierarchy
Jul 02, 2018 12:41:14 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@1059d4c6: display name [Root WebApplicationContext]; startup date [Mon Jul 02 12:41:14 UTC 2018]; root of context hierarchy
Jul 02, 2018 12:41:14 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@1059d4c6]: org.springframework.beans.factory.support.DefaultListableBeanFactory@16432224
Jul 02, 2018 12:41:14 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@16432224: defining beans [filter,legacy]; root of factory hierarchy
Jul 02, 2018 12:41:14 PM jenkins.model.Jenkins setSecurityRealm
FINE: Security is now fully set up
Jul 02, 2018 12:41:14 PM jenkins.model.Jenkins save
FINE: refusing to set version 2.121.1 to 2.121.1 during Loaded all jobs
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onTaskCompleted
FINE: Completed Finalizing set up
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Jul 02, 2018 12:41:14 PM jenkins.InitReactorRunner$1 onAttained
FINE: Attained Finalizing set up
Jul 02, 2018 12:41:14 PM jenkins.model.Jenkins save
FINE: setting version 2.121.1 to 2.121.1
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.udp => null
Jul 02, 2018 12:41:14 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.DNSMultiCast.disabled => null
Jul 02, 2018 12:41:14 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Jul 02, 2018 12:41:14 PM jenkins.slaves.restarter.JnlpSlaveRestarterInstaller install
FINE: Effective SlaveRestarter on : null
--> setting agent port for jnlp
Jul 02, 2018 12:41:24 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.TcpSlaveAgentListener.hostName => null
Jul 02, 2018 12:41:24 PM jenkins.util.SystemProperties getString
CONFIG: Property (not found): hudson.TcpSlaveAgentListener.port => null
--> setting agent port for jnlp... done
```

**Comment by oleg-nenashev** [comment]
Looks fine, jenkins has started up and read configuration from the volume.
So, what are current jenkins startup and curl command lines?

**Comment by pranshuverma** [comment]
`curl -v -I localhost:8080`

**Comment by oleg-nenashev** [comment]
do you curl it from the same machine?

**Comment by pranshuverma** [comment]
yes

**Comment by pranshuverma** [comment]
Above stuck command output for reference from container:
```
root@7173ad7f825d:/# curl -v -I localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> HEAD / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.52.1
> Accept: */*
>


```

**Comment by jcberthon** [comment]
This weekend we upgraded from 2.89.4 to 2.121.1. We have the same issue.

So our logs show only INFO message and then:

```
INFO: Jenkins is fully up and running
--> setting agent port for jnlp
--> setting agent port for jnlp... done
```

We can see that Jenkins is correctly listening on the socket:

```console
$ ss -ltpn
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port              
LISTEN     0      50           *:50000                    *:*                   users:(("java",pid=7,fd=749))
LISTEN     0      50           *:8080                     *:*                   users:(("java",pid=7,fd=160))
LISTEN     0      128    127.0.0.11:44793                    *:*                  
LISTEN     0      50           *:8443                     *:*                   users:(("java",pid=7,fd=235))
```

But Firefox times out on the external link, and `curl` also times out even when using the Docker container IP from the host.

**Comment by batmat** [comment]
Either I do not understand, or cannot reproduce. Just spawned a new instance using 2.121.1:

```
$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                               NAMES
66e09ec70988        jenkins/jenkins:2.121.1   "/sbin/tini -- /usr/…"   2 minutes ago       Up 2 minutes        0.0.0.0:8080->8080/tcp, 50000/tcp   amazing_jepsen
$ d exec -ti 66 curl localhost:8080
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Administer
-->

</body></html>
```

And I could also perfectly access Jenkins UI from my local browser.

**Comment by pranshuverma** [comment]
@batmat 
To add I am able to run the same on other centos 7 host and on my local mac machine. The issue is with host having KVM installed.
So it seems a host issue to me. But I do not see any error in logs for the container but the UI and curl is getting timed out. And I am able to run other application containers on the host.

Can you suggest the settings I can check and verify on the host.

**Comment by carlossg** [comment]
you probably have some issues with iptables or networking

**Comment by jcberthon** [comment]
We have the problem on the prod machine. On the staging machine, we spawn a Jenkins container with our configuration (I'm currently asking a colleague to understand how this configuration was different from prod) and it worked in staging. So we deployed the container in prod and there it fails.

I don't think it is related to KVM, because we have it on our staging machine, but not on our prod one.

As for networking that was our first bet. But the routing is alright, and when we use tshark to check the actual packets, we can see a client request going to the container IP on port 8080, we can see a packet going back to the client, we can see the HTTP get then going, but there are at TCP level answers (e.g. ACK, keep alive) but no answers at HTTP level.

Jenkins is clearly up and running, it is listening to port 8080. etc. all seems fine, logs is clean, etc. But we do not get HTTP answers...

What's puzzling is the same docker-compose.yml is being used in our staging machine and it works there.
Both staging and prod are running CentOS 7.5 (same patch level), running the same Docker CE release (18.03.1), on the same hardware, the same iptables, the same SELinux configuration. Only differences are: on prod we only run containers (tested on staging first) on staging we test newer version of prod containers and we tests also new services, on staging we have KVM with just 2 VM running. Obviously we do not have exactly same configurations between prod and staging for containers (e.g. when we test a build in staging we do not want it to send emails around or touch our prod Git repos or Sonar, etc.).

There is nothing in the logs of Jenkins.

**Comment by jcberthon** [comment]
Some info:

```
$ docker ps --format '{{.ID}} {{.Image}} {{.Command}}' --filter "name=spcbo_jenkins"
77dc7ea5ce7a spc-jenkins:2.126 "/sbin/tini -- /usr/…"
$ docker top spcbo_jenkins
UID                 PID                 PPID                C                   STIME               TTY                 TIME                               CMD
1000                121292              121276              0                   Jul09               ?                   00:00:03                           /sbin/tini -- /usr/local/bin/jenkins.sh
1000                121367              121292              0                   Jul09               ?                   00:08:10                           java -Duser.home=/var/jenkins_home -Xmx8g -Djava.io.tmpdir=/var/lib/jenkins/tmp -jar /usr/share/jenkins/jenkins.war --httpsPort=84               43 --httpsKeyStore=/certs/jenkins_keystore.jks --httpsKeyStorePassword=jenkins-pw
$ docker exec -t 77dc7ea5ce7a ss -ltpn
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
LISTEN     0      50           *:50000                    *:*                   users:(("java",pid=7,fd=752))
LISTEN     0      50           *:8080                     *:*                   users:(("java",pid=7,fd=160))
LISTEN     0      50           *:8443                     *:*                   users:(("java",pid=7,fd=235))
LISTEN     0      128    127.0.0.11:41570                    *:*
$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 77dc7ea5ce7a
172.26.0.4
$ curl -m 5 172.26.0.4:8080
curl: (28) Operation timed out after 5001 milliseconds with 0 out of -1 bytes received
```

And here is the tshark trace of that exchange:
```
$ tshark -i vethb6781ff
Capturing on 'vethb6781ff'
  1 0.000000000   172.26.0.1 -> 172.26.0.4   TCP 74 49502 > http-alt [SYN] Seq=0 Win=42340 Len=0 MSS=1460 SACK_PERM=1 TSval=179534320 TSecr=0 WS=4096
  2 0.000031265   172.26.0.4 -> 172.26.0.1   TCP 74 http-alt > 49502 [SYN, ACK] Seq=0 Ack=1 Win=43440 Len=0 MSS=1460 SACK_PERM=1 TSval=179534320 TSecr=179534320 WS=4096
  3 0.000052826   172.26.0.1 -> 172.26.0.4   TCP 66 49502 > http-alt [ACK] Seq=1 Ack=1 Win=45056 Len=0 TSval=179534320 TSecr=179534320
  4 0.000120642   172.26.0.1 -> 172.26.0.4   HTTP 145 GET / HTTP/1.1
  5 0.000130225   172.26.0.4 -> 172.26.0.1   TCP 66 http-alt > 49502 [ACK] Seq=1 Ack=80 Win=45056 Len=0 TSval=179534320 TSecr=179534320
  6 5.001526311   172.26.0.1 -> 172.26.0.4   TCP 66 49502 > http-alt [FIN, ACK] Seq=80 Ack=1 Win=45056 Len=0 TSval=179539321 TSecr=179534320
  7 5.040635089   172.26.0.4 -> 172.26.0.1   TCP 66 http-alt > 49502 [ACK] Seq=1 Ack=81 Win=45056 Len=0 TSval=179539361 TSecr=179539321
```

You can see that there is a communication happening at TCP level. First the handshake, then the HTTP Get, the Ack from that Get, then nothing for 5 sec, then curl terminates the connection.

If I would not have used `-m 5` in curl, we would only then see keep-alives and nothing else.

The weird thing is only the web interface is not accessible. Obviously jenkins is executing jobs properly.

**Comment by jcberthon** [comment]
OK I wanted to try `tshark` from within the container.

So after installing it inside the container, I got permission denied even as root. So I recreated the container using the NET_RAW and NET_ADMIN capabilities which are required for tshark to operate.

I've run a trace in the loopback while running curl from within the container, surprised it worked.

Then I tried to access Jenkins from Firefox, and this time it worked.

**I have tried and only the NET_ADMIN capabilities is required to make it work.**

What is puzzling me is why in staging we do not need this extra capabilities and in prod we need it? And why is there no errors?

**Comment by sofat1989** [comment]
@pranshuverma I also met this issue in the jenkinsci/jenkins:2.121.1. Same Dockefile and lauch parameters work in the  jenkinsci/jenkins:2.107.3
```
root@kube-jenkins-lcvtc:/# ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root         1     0  0  80   0 -   286 sigtim 07:51 ?        00:00:00 tini -- /usr/local/bin/volume-permissions.sh
4 S root         9     0  0  80   0 -  4994 poll_s 07:52 ?        00:00:00 bash
4 S jenkins     18     1  9  80   0 - 12823681 futex_ 07:53 ?     00:05:02 java -Duser.home=/var/jenkins_home -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true -Duser.home=/root -jar /usr/share/jenkins/jenkins.war
4 S root      3486     0  0  80   0 -  4994 wait   08:43 ?        00:00:00 bash
0 R root      3518  3486  0  80   0 -  9595 -      08:44 ?        00:00:00 ps -elf
```
The lauch command is
```
java -Duser.home=/var/jenkins_home -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true -Duser.home=/root -jar /usr/share/jenkins/jenkins.war --httpsKeyStore=/docker-java-home/jre/lib/security/jenkins.jks--httpsKeyStorePassword=***  --httpsPort=8443 --httpPort=8001
```
The java process is in the Sleep Status. I cannot access the pods via 8443 and 8001. No failure logs shown in the logs
```
****
Jul 17, 2018 8:32:14 AM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@13ae7659{HTTP/1.1,[http/1.1]}{0.0.0.0:8001}
Jul 17, 2018 8:32:14 AM org.eclipse.jetty.util.ssl.SslContextFactory load
INFO: x509=X509@a50b09c(lp-10db832a-087f-4c8b-96ac-efd499072c52,h=[],w=[]) for SslContextFactory@4da855dd(null,null)
Jul 17, 2018 8:32:14 AM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@2afa3516{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
***
Jul 17, 2018 8:32:28 AM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
--> setting agent port for jnlp
--> setting agent port for jnlp... done
```

However, I removed the flag ` --httpsPort=8443`, Run the command below in the container
```
java -Duser.home=/var/jenkins_home -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true -Duser.home=/root -jar /usr/share/jenkins/jenkins.war --httpsKeyStore=/docker-java-home/jre/lib/security/jenkins.jks--httpsKeyStorePassword=***   --httpPort=8002
```
then we can access the 8002 via Browser.
```
$ curl -I 10.147.169.104:8002
HTTP/1.1 200 OK
Date: Tue, 17 Jul 2018 09:03:18 GMT
X-Content-Type-Options: nosniff
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache,no-store,must-revalidate
X-Hudson-Theme: default
Content-Type: text/html;charset=utf-8
Set-Cookie: JSESSIONID.7456b9a3=node0nxj5u4l3tl4vp6h0lhmlpipj0.node0;Path=/;HttpOnly
X-Hudson: 1.395
X-Jenkins: 2.121.1
X-Jenkins-Session: 52a09ba0
X-Frame-Options: sameorigin
X-Instance-Identity: ***
Content-Length: 19048
Server: Jetty(9.4.z-SNAPSHOT)
```
I saw the command pasted by @jcberthon above. He also specified the `httpsPort`.  
So do you think whether httpsPort flag causes this issue?

**Comment by pranshuverma** [comment]
@sofat1989 
I am using jenkins/jenkins:lts image and not jenkinsci/jenkins:2.121.1.

Also I am facing this issue in one host with KVM setup there. On other host vms I am able to get it up and running completely fine.

I tried the command you listed but still facing same issue on the host. So I feel in my case the host networking is culprit. I am still debugging and will update the issue if I find anything relevant.

**Comment by skeenan947** [comment]
We're seeing the same issue - upgraded from 2.107.3 to 2.121.1/2, and jenkins comes up, says everything is alright, listens on http, but never responds to any http requests...  rolled back one instance and it started working again.

**Comment by sofat1989** [comment]
@pranshuverma @skeenan947 I tried other hosts. I found the Jenkins cannot be up in the hosts whose CPU cores are more than 32 (including 32). I tried 16 cores and 4 cores hosts. It can be up and runs well. How about the SKU of your hosts?

**Comment by sofat1989** [comment]
In order to get rid of the  impacts from docker, so i directyly run the command in the hosts. Here i listed the results.
The results show that enabling httpsPort in the hosts which has a lot of cpu cores will make jenkins not work.

| OS  | CPU cores  | enable httpPort  | enable  HttpsPort | Command  | Result|
|---|---|---|---|---|---|
|  Centos | 4  | Y  | Y   | java -jar /usr/share/jenkins/jenkins.war --httpPort=8005  --httpsPort=8447  | Works well|
|Centos   |   16|  Y | Y   |   java -jar /usr/share/jenkins/jenkins.war --httpPort=8005  --httpsPort=8447  |Works well|
|  Centos | 32  | Y  | Y   |  java -jar /usr/share/jenkins/jenkins.war --httpPort=8005  --httpsPort=8447   |Cannot curl|
|  Centos | 32  | Y  | N   |  java -jar /usr/share/jenkins/jenkins.war --httpPort=8005     | Works well|
|  Ubuntu | 16  | Y  | Y   |  java -jar /usr/share/jenkins/jenkins.war --httpPort=8005   --httpsPort=8447   | Works well|
|  Ubuntu | 32  | Y  | Y   |  java -jar /usr/share/jenkins/jenkins.war --httpPort=8005   --httpsPort=8447   |  Cannot curl|
|  Ubuntu | 32  | Y  | N   |  java -jar /usr/share/jenkins/jenkins.war --httpPort=8005     | Works well|

**Comment by pranshuverma** [comment]
@sofat1989  My host has 72 cores and it is Centos 7 based host and I am not enabling https port for jenkins.

**Comment by rodrigc** [comment]
@sofat1989 If you try to restrict the number of CPU's with the `--cpus=` flag to `docker run`  as specified here: https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler

does that change anything?

**Comment by rodrigc** [comment]
Similar problem reported here https://smartos.org/bugview/OS-5165

**Comment by sofat1989** [comment]
@rodrigc I tried this. This will not change the results.

**Comment by skeenan947** [comment]
so unlike some folks here, I don't have https on (a k8s ingress in front of jenkins is taking care of ssl).
The host this is running on has 72 cores, so the cpu cores thing could be the problem.

**Comment by rodrigc** [comment]
@skeenan947 can you add your findings to 
https://issues.jenkins-ci.org/browse/JENKINS-33412 ?

**Comment by jcberthon** [comment]
On our host we have 2 CPUs with 12 cores each, so 24 cores total. And we do have the problem. And as @sofat1989 mentionned we do use `httpsPort`.

We do limit the number of CPU at Docker level, it is currently limited to 12. But as @skeenan947 stated, this is just a cgroup configuration, it does not change the number of CPU cores (e.g. the output of `lscpu` is unchanged by the cgroup configuration).

**Comment by jcberthon** [comment]
The above explain why the upgrade work in staging but not in prod. In staging we have the same hardware (so total 24 cores) but we do not use `--httpsPort` flag.

Our team just tested in staging using the flag, just like prod, and it fails as well.

So it seems to be a combination of the flag and the number of cores, as reported by others here.

**Comment by skeenan947** [comment]
I do not use httpsPort, and have the same issue.  Larger number of CPUs
though.

**Comment by skholod** [comment]
We have 120 cores, no specific http(s) settings - 8080 only by default, container is custom but nothing specific besides simple debian and "java -jar jenkins.war".
Web interface of 2.121.3 doesn't come up.
Reverting back to 2.107.3 help to solve the problem.

**Comment by rodrigc** [comment]
@skholod @skeenan947 @jcberthon @sofat1989 can you try the war file at [JENKINS-33412 comment 347111](https://issues.jenkins-ci.org/browse/JENKINS-33412?focusedCommentId=347111&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-347111) which tries to solve the problem?

**Comment by skeenan947** [comment]
yes!  this is working.
Published a hand-built container at `skeenan947/jenkinstest` if anyone else wants to test it out without having to build it.

**Comment by skeenan947** [comment]
I know it's a bit early to ask :D but I'm curious when this change might make it into an LTS version?

**Comment by carlossg** [comment]
Depends on https://github.com/jenkinsci/winstone/pull/54

**Comment by rodrigc** [comment]
@skeenan947 can you add the details about your environment and testing to [JENKINS-33412](https://issues.jenkins-ci.org/browse/JENKINS-33412) and ask about possible LTS there?

**Comment by jcberthon** [comment]
My colleague performed the test with the new war file. Test successful, Jenkins work on our system. 👍

**Comment by sujumayas** [comment]
This Thread has been really interesting, and I have spent almost 3 days "fixing" this problem. I had a different reason for my problem, which allowed me to curl localhost jenkins in the production server, but it just keep loading on browsers in my local machine. 

I post this so people that are new to DevOps like me... if they see this msg they will not stay 3 days trying to fix a much deeper problem when they only needed to **allow the 8080 port on ec2 security group configuration.** 

Hope this can help someone from the pain.

**Comment by kairaazure** [comment]
Hi sujamayas i have the same issue as mentioned above ,can you please help me to suggest it for gcp also where i need to allow 8080 port on gcp??
Thanks in advance. :)

**Comment by ufp1000** [comment]
> This Thread has been really interesting, and I have spent almost 3 days "fixing" this problem. I had a different reason for my problem, which allowed me to curl localhost jenkins in the production server, but it just keep loading on browsers in my local machine.
> 
> I post this so people that are new to DevOps like me... if they see this msg they will not stay 3 days trying to fix a much deeper problem when they only needed to **allow the 8080 port on ec2 security group configuration.**
> 
> Hope this can help someone from the pain.

Thanks @sujumayas
